building_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('management.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'management'

urlpatterns = [
    url(r'^home/$', views.index, name='home'),
    url(r'^whatis/$', views.whatis, name='whatis'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signup/account-activation/(?P<uid_base_64>[0-9a-zA-Z_\-]+)/(?P<token>[0-9a-zA-Z]{1,13}-[0-9a-zA-Z]{1,20})/$',
        views.activate_account, name='account-activation'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^manager_account/$', views.manager_account, name='manager_account'),
    url(r'^payment_initial/$', views.payment_initial, name='payment_initial'),
    url(r'^payment_final/$', views.payment_final, name='payment_final'),
    url(r'^buildings/$', views.buildings, name='buildings'),
    url(r'^buildings/(?P<building_id>[0-9]+)/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^buildings/(?P<building_id>[0-9]+)/messaging/$', views.messaging, name='messaging'),
    ## temporary
     # url(r'^buildings/(?P<building_id>[0-9]+)/bills/$', views.bills, name='bills'),
    ## temporary
    url(r'^buildings/(?P<building_id>[0-9]+)/messaging/sent_messages/$', views.messaging_sent, name='messaging_sent'),
    url(r'^buildings/(?P<building_id>[0-9]+)/bulletin_board/$', views.bulletin_board, name='bulletin_board'),
    url(r'^buildings/(?P<building_id>[0-9]+)/bulletin_board/(?P<bulletin_id>[0-9]+)/delete/$',
        views.delete_bulletin, name='delete_bulletin'),
    # url(r'^buildings/(?P<building_id>[0-9]+)/facility_info/$', views.facility_info, name='facility_info'),
    # url(r'^dashboard_user/$', views.dashboard_user, name='dashboard_user'),
    url(r'^buildings/(?P<building_id>[0-9]+)/edit/', views.BuildingUpdate, name='update_building'),
    url(r'^buildings/(?P<building_id>[0-9]+)/units/$', views.building_units, name='building_units'),
    url(r'^buildings/(?P<building_id>[0-9]+)/units/(?P<unit_id>[0-9]+)/delete/$', views.delete_unit,
        name='delete_unit'),
    url(r'^buildings/(?P<building_id>[0-9]+)/facilities/$', views.facilities, name='facilities'),
    url(r'^buildings/(?P<building_id>[0-9]+)/facilities/(?P<facility_id>[0-9]+)/delete/$', views.delete_facility,
        name='delete_facility'),
    url(r'^buildings/(?P<building_id>[0-9]+)/facilities/(?P<facility_id>[0-9]+)/facility_info/$', views.facility_info,
        name='facility_info'),
    url(r'^buildings/(?P<building_id>[0-9]+)/delete/$', views.delete_building, name="delete_building"),
    url(r'^cost/new/$', views.new_cost, name="new_cost"),


    url(r'^user_account/$', views.user_account, name='user_account'),
    url(r'^my_units/$', views.user_units, name='user_units'),
    url(r'^my_units/(?P<unit_id>[0-9]+)/dashboard', views.dashboard_user, name='dashboard_user'),
    url(r'^my_units/(?P<unit_id>[0-9]+)/bills/$', views.bills, name='bills'),
    url(r'^my_units/(?P<unit_id>[0-9]+)/bills/(?P<bill_id>[0-9]+)/payment_inital/$', views.payment_initial,
        name='payment_initial'),
    url(r'^my_units/(?P<unit_id>[0-9]+)/bills/(?P<bill_id>[0-9]+)/payment_final/$', views.payment_final,
        name='payment_final'),
    url(r'^my_units/(?P<unit_id>[0-9]+)/facilities/$', views.user_facilities, name='user_facilities'),
    url(r'^my_units/(?P<unit_id>[0-9]+)/facilities/(?P<facility_id>[0-9]+)/facility_info/$', views.user_facility_info,
        name='user_facility_info'),
]

management/models.py
import datetime
from django.utils import timezone
from . import jdate

import math

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings

# max lengths
names_length = 60
address_length = 300
short_description_length = 500
long_description_length = 1000


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=names_length)
    mobile_number = models.CharField(max_length=11)
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)
    is_manager = models.BooleanField(default=True)

    def __str__(self):
        return self.full_name + ' ' + self.mobile_number


class Building(models.Model):
    name = models.CharField(max_length=names_length)
    address = models.CharField(max_length=address_length)
    description = models.TextField(max_length=long_description_length)
    number_of_floors = models.IntegerField()
    number_of_elevators = models.IntegerField()
    # main_pic_src = models.CharField(max_length=5000, null=True, blank=True)
    main_pic = models.FileField(upload_to='building_images', default='../static/building_default.png')
    balance = models.IntegerField(default=0)
    manager = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    end_of_subscription = models.DateTimeField(null=True)


class Unit(models.Model):
    # types
    RESIDENTIAL = 'R'
    BUSINESS = 'B'
    TYPE_CHOICES = (
        (RESIDENTIAL, 'مسکونی'),
        (BUSINESS, 'تجاری'),
    )
    unit_type = models.CharField(max_length=1,
                                 choices=TYPE_CHOICES,
                                 default=RESIDENTIAL)
    unit_number = models.PositiveIntegerField()
    story = models.IntegerField()
    area = models.PositiveIntegerField()  # unit: m^2
    number_of_bedrooms = models.PositiveIntegerField(default=1)
    number_of_parking_spaces = models.PositiveIntegerField(default=1)
    number_of_storage_rooms = models.PositiveIntegerField(default=1)
    description = models.TextField(blank=True, null=True)
    options = models.CharField(max_length=short_description_length, blank=True, null=True)
    main_pic = models.FileField(upload_to='unit_images', default='../../../static/unit_default.png')

    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, blank=True, null=True, related_name='owned_units')
    number_of_residents = models.PositiveIntegerField(validators=[MinValueValidator(1)], default=2)
    ownership_info = models.TextField(max_length=long_description_length, blank=True, null=True)
    rental_status = models.BooleanField(default=False)
    tenant = models.ForeignKey(Profile, on_delete=models.SET_NULL, blank=True, null=True, related_name='rented_units')


class Pictures(models.Model):
    image = models.ImageField(upload_to='media/building_and_unit_pics')

    building = models.ForeignKey(Building, on_delete=models.CASCADE, null=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True)


class Bill(models.Model):
    # todo: types? types should be determined
    description = models.TextField(max_length=short_description_length)
    fee = models.IntegerField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    due_date_time = models.DateTimeField()
    is_paid = models.BooleanField(default=False)


class Facility(models.Model):
    name = models.CharField(max_length=names_length)
    description = models.TextField(max_length=long_description_length)
    main_pic = models.FileField(upload_to='unit_images', default='../../../static/facility_default.png')
    cost_per_hour = models.PositiveIntegerField()

    building = models.ForeignKey(Building, on_delete=models.CASCADE)


class OneHourReserve(models.Model):
    hour_number = models.PositiveIntegerField(validators=[MaxValueValidator(23)])
    reservation_status = models.PositiveIntegerField(validators=[MaxValueValidator(2)], default=0)
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)


class FacilityReservation(models.Model):
    reservee = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    # todo: confirmation status may not be necessary
    confirmation_status = models.BooleanField(default=False)
    bill = models.ForeignKey(Bill, on_delete=models.SET_NULL, null=True)


# todo: may not be needed at all
class Janitor(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    duty = models.CharField(max_length=names_length)
    contract_info = models.TextField(max_length=long_description_length)


# todo: should be taken care of later
class Cost(models.Model):
    date = models.DateTimeField()
    fee = models.IntegerField()
    description = models.TextField(max_length=short_description_length)

    building = models.ForeignKey(Building, on_delete=models.CASCADE)

    def bill_based_on_area(self):
        units = self.building.unit_set.all()
        area_sum = units.aggregate(Sum('area'))['area__sum']
        for unit in units:
            fee = math.floor(self.fee * unit.area / area_sum)
            bill = Bill(description=self.description, fee=fee,
                        due_date_time=timezone.now() + datetime.timedelta(weeks=1),
                        unit=unit)
            bill.save()

    def bill_based_on_unit(self):
        units = self.building.unit_set.all()
        number_of_units = units.count()
        for unit in units:
            fee = math.floor(self.fee / number_of_units)
            bill = Bill(description=self.description, fee=fee,
                        due_date_time=timezone.now() + datetime.timedelta(weeks=1),
                        unit=unit)
            bill.save()

    def bill_based_on_number_of_residents(self):
        units = self.building.unit_set.all()
        residents_sum = units.aggregate(Sum('number_of_residents'))['number_of_residents__sum']
        for unit in units:
            fee = math.floor(self.fee * unit.number_of_residents / residents_sum)
            bill = Bill(description=self.description, fee=fee,
                        due_date_time=timezone.now() + datetime.timedelta(weeks=1),
                        unit=unit)
            bill.save()


class Bulletin(models.Model):
    title = models.CharField(max_length=2 * names_length)
    text = models.TextField(max_length=3 * long_description_length)
    date_time = models.DateTimeField()

    building = models.ForeignKey(Building, on_delete=models.CASCADE)

    @property
    def jalali_date(self):
        dt = self.date_time
        jd = jdate.gregorian_to_jd(dt.year, dt.month, dt.day)
        jalalidate = jdate.jd_to_persian(jd)
        return '' + str(math.floor(jalalidate[0])) + '/' + str(math.floor(jalalidate[1])) + '/' + \
               str(math.floor(jalalidate[2]))

    @property
    def jalali_time(self):
        return '' + str(self.date_time.hour) + ':' + str(self.date_time.minute)


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='sent_messages')
    receiver = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='received_messages')
    date_time = models.DateTimeField()
    title = models.CharField(max_length=2 * names_length)
    text = models.TextField(max_length=3 * long_description_length)
    # confirmation status may not be needed

management/forms.py
from django import forms
from .models import Building, Unit, Facility, Profile, Cost, Bulletin, Message


class BuildingForm(forms.ModelForm):
    class Meta:
        model = Building
        fields = ('name', 'address', 'description', 'number_of_floors', 'number_of_elevators', 'main_pic', 'balance')

    def __init__(self, *args, **kwargs):
        super(BuildingForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "نام"
        self.fields['address'].label = "آدرس"
        self.fields['description'].label = "توضیح"
        self.fields['number_of_floors'].label = "تعداد طبقات"
        self.fields['number_of_elevators'].label = "تعداد آسانسورها"
        self.fields['balance'].label = "موجودی اولیه"
        self.fields['main_pic'].label = "انتخاب تصویر"


class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ('unit_type', 'unit_number', 'story', 'area', 'number_of_bedrooms', 'number_of_parking_spaces',
                  'number_of_storage_rooms', 'options', 'description', 'owner', 'main_pic')

    def __init__(self, *args, **kwargs):
        super(UnitForm, self).__init__(*args, **kwargs)
        self.fields['unit_type'].label = "نوع واحد"
        self.fields['unit_number'].label = "شماره‌ی واحد"
        self.fields['story'].label = "طبقه"
        self.fields['area'].label = "مساحت"
        self.fields['number_of_bedrooms'].label = "تعداد اتاق خواب"
        self.fields['number_of_parking_spaces'].label = "تعداد پارکینگ"
        self.fields['number_of_storage_rooms'].label = "تعداد انباری"
        self.fields['options'].label = "امکانات"
        self.fields['description'].label = "توضیح"
        self.fields['owner'].label = "مالک"
        self.fields['main_pic'].label = "انتخاب تصویر"


class FacilityForm(forms.ModelForm):
    class Meta:
        model = Facility
        fields = ('name', 'description', 'cost_per_hour')

    def __init__(self, *args, **kwargs):
        super(FacilityForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "نام"
        self.fields['description'].label = "توضیحات"
        self.fields['cost_per_hour'].label = "نرخ اجاره به ازای هر نیم ساعت"


class CostForm(forms.ModelForm):
    TYPE_CHOICES = (
        ('number_of_unit', 'تعداد واحد'),
        ('number_of_people', 'تعداد نفر'),
        ('area', 'مساحت'),
    )
    building_id = forms.IntegerField(label="", widget=forms.HiddenInput(), required=True)
    should_be_billed = forms.BooleanField(label="برای این هزینه قبض صادر شود؟", required=False)
    bill_type = forms.CharField(label="صدور قبض براساس", widget=forms.Select(choices=TYPE_CHOICES), required=True)

    class Meta:
        model = Cost
        fields = ('fee', 'description', 'building_id', 'should_be_billed', 'bill_type')

    def __init__(self, *args, **kwargs):
        super(CostForm, self).__init__(*args, **kwargs)
        self.fields['fee'].label = "مبلغ پرداختی"
        self.fields['description'].label = "توضیحات"


class BulletinForm(forms.ModelForm):
    class Meta:
        model = Bulletin
        fields = ('title', 'text')

    def __init__(self, *args, **kwargs):
        super(BulletinForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = "عنوان"
        self.fields['text'].label = "متن"

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('receiver', 'title', 'text')

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = "عنوان"
        self.fields['receiver'].label = "گیرنده"
        self.fields['text'].label = "متن پیام"

management/templates/management/base_user.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>داشبورد | پنل کاربری</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Loading bootstrap css-->
    <link type="text/css" rel="stylesheet"
          href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,700">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
    <link type="text/css" rel="stylesheet" href="{% static "styles/jquery-ui-1.10.4.custom.min.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/font-awesome.min.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/bootstrap.min.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/animate.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/all.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/main.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/style-responsive.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/zabuto_calendar.min.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/pace.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "styles/jquery.news-ticker.css" %}">
    <style>
        * {
            direction: rtl;
        !important;
        }
    </style>
</head>
<body>


<!--BEGIN BACK TO TOP-->
<a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
<!--END BACK TO TOP-->
<!--BEGIN TOPBAR-->
<div id="header-topbar-option-demo" class="page-header-topbar">
    <nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3"
         class="navbar navbar-default navbar-static-top">
        <div class="navbar-header">
            <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span
                    class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span
                    class="icon-bar"></span></button>
            <a id="logo" href="dashboard.html" class="navbar-brand"><span class="fa fa-rocket">  </span><span
                    class="logo-text"><img src="{% static "logo/sima_logo_captionless.png" %}" class=""
                                           style="width: 40px"/> سیما</span><span style="display: none"
                                                                                  class="logo-text-icon">µ</span></a>
        </div>
        <div class="topbar-main"><a id="menu-toggle" href="#" class="hidden-xs"><i class="fa fa-bars"></i></a>
            <div class="news-update-box hidden-xs">
                <ul id="news-update" class="ticker list-unstyled">
                    <li style="color : white">محمدمهدی فاریابی عزیز خوش آمدید. سیما, سامانه یکپارچه مدیریت آپارتمان</li>
                </ul>
            </div>
            <ul class="nav navbar navbar-top-links navbar-right mbn">
                <li class="dropdown"><a data-hover="dropdown" href="#" class="dropdown-toggle"><i
                        class="fa fa-bell fa-fw"></i><span class="badge badge-yellow">3</span></a>

                </li>
                <li class="dropdown"><a data-hover="dropdown" href="#" class="dropdown-toggle"><i
                        class="fa fa-envelope fa-fw"></i><span class="badge badge-orange">7</span></a>

                </li>

                </li>
                <li class="dropdown topbar-user"><a data-hover="dropdown" href="#" class="dropdown-toggle"><img
                        src="https://pbs.twimg.com/profile_images/546708662287228929/XK0Jznql_400x400.jpeg" alt="" class="img-responsive img-circle"/>&nbsp;<span
                        class="hidden-xs">محمد مهدی فاریابی</span>&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu dropdown-user pull-right">
                        <li><a href="{% url 'management:user_account' %}"><i class="fa fa-user"></i>حساب کاربری من</a></li>
                        <li><a href="{% url 'management:user_units' %}"><i class="fa fa-home"></i>واحد‌های من</a></li>
{#                        <li><a href="#"><i class="fa fa-envelope"></i>پیام‌های دریافتی<span class="badge badge-danger">3</span></a>#}
{#                        </li>#}
{#                        <li><a href="#"><i class="fa fa-tasks"></i>فعالیت‌ها<span#}
{#                                class="badge badge-success">7</span></a></li>#}
                        <li class="divider"></li>
                        <!--<li><a href="#"><i class="fa fa-lock"></i>Lock Screen</a></li>-->
                        <li><a href="{% url 'management:logout' %}"><i class="fa fa-key"></i>خروج از سامانه</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</div>
<!--END TOPBAR-->

<div id="wrapper">
    <!--BEGIN SIDEBAR MENU-->
    <nav id="sidebar" role="navigation" data-step="2"
         data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;"
         data-position="right" class="navbar-default navbar-static-side">
        <div class="sidebar-collapse menu-scroll">
            <ul id="side-menu" class="nav">

                <div class="clearfix"></div>
                <li class="active"><a href="{% url 'management:dashboard_user' unit.id %}"><i class="fa fa-tachometer fa-fw">
                    <div class="icon-bg bg-orange"></div>
                </i><span class="menu-title">داشبورد - واحد ۳</span></a></li>


                <li><a data-toggle="collapse"  href="#collapse1"><i class="fa fa-desktop fa-fw">
                    <div class="icon-bg bg-pink"></div>
                </i><span class="menu-title ">ساختمان</span></a>
                </li>
                        <div id="collapse1" class="sublinks collapse list-group">
                            <a class="list-group-item small" href="{% url 'management:bills' unit.id %}">پرداخت قبوض</a>
{#                            <a class="list-group-item small" href="">دریافت سوابق مالی</a>#}
                            <a class="list-group-item small" href="">رزرو امکانات ساختمان</a>
                        </div>



                <li><a data-toggle="collapse" href="#collapse8"><i class="fa fa-envelope-o fa-fw">
                    <div class="icon-bg bg-grey"></div>
                </i>
                    <span class="menu-title">پیام رسانی</span></a>

                </li>
                <div id="collapse8" class="sublinks collapse list-group">
                    <a class="list-group-item small" href="">">تابلو‌ی اعلانات</a>
                    <a class="list-group-item small" href="">پیام‌های دریافتی</a>
                    <a class="list-group-item small" href="">پیام‌های ارسالی</a>
                </div>
            </ul>
        </div>
    </nav>
    <!--END SIDEBAR MENU-->


    <div id="page-wrapper">

        {% block content %}

        {% endblock %}

    </div>



<footer>
    <div class="container-fluid text-center">
        <a class="brand" href="#"></a>
    </div>
    <div class="container-fluid text-center">
        <nav class="navbar-collapse">
            <ul id="menu-main-menu-1" class="nav navbar-nav"><li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-83"><a href="{% url 'management:whatis' %}">سیما چیست؟</a></li>
                {#<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-17"><a href="/login">ورود به سامانه</a></li>#}
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-13"><a href="{% url 'management:home' %}">صفحه‌ی اصلی</a></li>
            </ul>
        </nav>
    </div>
</footer>




<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net",
    "licenseKey":"afa4101d8d","applicationID":"11530091","transactionName":"NFxSMEtRXURYBUJQCw0WcQdNWVxZFgBEVgoXFEAFXlU=",
    "queueTime":3,"applicationTime":252,"atts":"GBtRRgNLTko=","errorBeacon":"bam.nr-data.net","agent":""}</script>




</div>
<script src="{% static "script/jquery-1.10.2.min.js" %}"></script>
<script src="{% static "script/jquery-migrate-1.2.1.min.js" %}"></script>
<script src="{% static "script/jquery-ui.js" %}"></script>
<script src="{% static "script/bootstrap.min.js" %}"></script>
<script src="{% static "script/bootstrap-hover-dropdown.js" %}"></script>
<script src="{% static "script/html5shiv.js" %}"></script>
<script src="{% static "script/respond.min.js" %}"></script>
<script src="{% static "script/jquery.metisMenu.js" %}"></script>
<script src="{% static "script/jquery.slimscroll.js" %}"></script>
<script src="{% static "script/jquery.cookie.js" %}"></script>
<script src="{% static "script/icheck.min.js" %}"></script>
<script src="{% static "script/custom.min.js" %}"></script>
<script src="{% static "script/jquery.news-ticker.js" %}"></script>
<script src="{% static "script/jquery.menu.js" %}"></script>
<script src="{% static "script/pace.min.js" %}"></script>
<script src="{% static "script/holder.js" %}"></script>
<script src="{% static "script/responsive-tabs.js" %}"></script>
<script src="{% static "script/jquery.flot.js" %}"></script>
<script src="{% static "script/jquery.flot.categories.js" %}"></script>
<script src="{% static "script/jquery.flot.pie.js" %}"></script>
<script src="{% static "script/jquery.flot.tooltip.js" %}"></script>
<script src="{% static "script/jquery.flot.resize.js" %}"></script>
<script src="{% static "script/jquery.flot.fillbetween.js" %}"></script>
<script src="{% static "script/jquery.flot.stack.js" %}"></script>
<script src="{% static "script/jquery.flot.spline.js" %}"></script>
<script src="{% static "script/zabuto_calendar.min.js" %}"></script>
<script src="{% static "script/index.js" %}"></script>
<!--LOADING SCRIPTS FOR CHARTS-->
<script src="{% static "script/highcharts.js" %}"></script>
<script src="{% static "script/data.js" %}"></script>
<script src="{% static "script/drilldown.js" %}"></script>
<script src="{% static "script/exporting.js" %}"></script>
<script src="{% static "script/highcharts-more.js" %}"></script>
<script src="{% static "script/charts-highchart-pie.js" %}"></script>
<script src="{% static "script/charts-highchart-more.js" %}"></script>
<!--CORE JAVASCRIPT-->
<script src="{% static "script/main.js" %}"></script>
<script>        (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
    a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
ga('create', 'UA-145464-12', 'auto');
ga('send', 'pageview');


</script>
</body>




{#start of bootstrap notify scripts#}
<script src="{% static "script/bootstrap-notify-3.1.3/bootstrap-notify.js" %}"></script>
<script src="{% static "script/bootstrap-notify-3.1.3/Gruntfile.js" %}"></script>
<script src="{% static "script/bootstrap-notify-3.1.3/package.js" %}"></script>
<script src="{% static "script/bootstrap-notify-3.1.3/test_meteor.js" %}"></script>
<script src="{% static "script/bootstrap-notify-3.1.3/dist/bootstrap-notify.js" %}"></script>
<script src="{% static "script/bootstrap-notify-3.1.3/dist/bootstrap-notify.min.js" %}"></script>
{#end of bootstrap notify scripts#}


</html>